---
version: '3.7'
services:
  # Service image
  app:
    image: dockertest:latest
    build:
      context: .azure-pipelines/docker
    volumes:
      - type: bind
        source: .
        target: /workspace
